
WAV_SIZE = 16000
label_to_num = {
    "bed": 0,
    "bird": 0,
    "cat": 0,
    "dog": 0,
    "down": 0,
    "eight": 0,
    "five": 0,
    "four": 0,
    "go": 0,
    "happy": 0,
    "house": 0,
    "left": 0,
    "marvin": 0,
    "nine": 0,
    "no": 0,
    "off": 0,
    "on": 0,
    "one": 0,
    "right": 0,
    "seven": 0,
    "sheila": 0,
    "six": 0,
    "stop": 0,
    "three": 0,
    "tree": 0,
    "two": 0,
    "up": 0,
    "wow": 0,
    "yes": 0,
    "zero": 0,
}